#!/usr/bin/env bash
# MCL global installer.
#
# Clones (or updates) the MCL library into ~/.mcl/lib and links the
# mcl-claude wrapper into ~/.local/bin (override with MCL_BIN).
#
# Idempotent — safe to re-run for upgrades.
#
# Usage:
#   bash install.sh
#   curl -sSL https://raw.githubusercontent.com/YZ-LLM/my-claude-lang/main/install.sh | bash
#
# Env overrides:
#   MCL_HOME  (default: ~/.mcl)
#   MCL_BIN   (default: ~/.local/bin)
#   MCL_REPO  (default: https://github.com/YZ-LLM/my-claude-lang)

set -euo pipefail

MCL_HOME="${MCL_HOME:-$HOME/.mcl}"
LIB="$MCL_HOME/lib"
BIN="${MCL_BIN:-$HOME/.local/bin}"
REPO="${MCL_REPO:-https://github.com/YZ-LLM/my-claude-lang}"

mkdir -p "$MCL_HOME/projects"
mkdir -p "$BIN"

if [ -d "$LIB/.git" ]; then
  echo "Updating MCL at $LIB ..."
  # Discard any previous {{MCL_VERSION}} substitutions in skill files so
  # `git pull --ff-only` doesn't trip on locally-modified tracked files.
  # The substitutions are re-applied below after pull lands the new VERSION.
  git -C "$LIB" checkout -- skills/ 2>/dev/null || true
  git -C "$LIB" pull --ff-only
else
  if [ -e "$LIB" ]; then
    echo "install.sh: $LIB exists but is not a git repo. Aborting to avoid clobbering." >&2
    exit 1
  fi
  echo "Cloning MCL into $LIB ..."
  git clone "$REPO" "$LIB"
fi

chmod +x "$LIB/bin/mcl-claude"
ln -sf "$LIB/bin/mcl-claude" "$BIN/mcl-claude"

version="$(cat "$LIB/VERSION" 2>/dev/null || echo unknown)"

# Substitute {{MCL_VERSION}} placeholder in skill files with the actual
# release version. Skill markdown is loaded as-is by Claude Code, so the
# version is baked in at install time. Source repo keeps the placeholder
# so the tracked tree never goes stale across releases.
if [ "$version" != "unknown" ] && [ -d "$LIB/skills" ]; then
  # macOS sed needs `-i ''`; GNU sed accepts `-i`. Use a portable -i.bak
  # then remove the .bak files.
  find "$LIB/skills" -name '*.md' -print0 \
    | xargs -0 sed -i.bak "s/{{MCL_VERSION}}/${version}/g"
  find "$LIB/skills" -name '*.md.bak' -delete
fi

# Invalidate the upstream-version cache so the next session re-fetches
# and the "X.Y.Z mevcut" notice reflects current upstream rather than
# whatever was cached pre-update. The cache file is regenerated by the
# next mcl-activate run.
rm -f "$HOME/.claude/cache/mcl-version.json" 2>/dev/null || true
echo
echo "✓ MCL $version installed → $BIN/mcl-claude"
echo "✓ Library: $LIB"
echo "✓ Per-project state: $MCL_HOME/projects/<key>/"
echo
echo "Usage:  cd <your-project> && mcl-claude"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *)
    echo
    echo "⚠  $BIN is not in your PATH."
    echo "   Add this to your shell rc (~/.bashrc, ~/.zshrc):"
    echo "     export PATH=\"$BIN:\$PATH\""
    ;;
esac
